# Generated by Django 4.2.2 on 2023-06-15 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [

            migrations.CreateModel(name='Cart',
                                   fields=[('id', models.BigAutoField(
                                               auto_created=True,
                                               primary_key=True,
                                               serialize=False,
                                               verbose_name='ID')),
                                           ('total_price', models.DecimalField(
                                               decimal_places=2,
                                               max_digits=8)),
                                           ('quantity', models.IntegerField()),
                                           ('user',
                                            models.OneToOneField(
                                                on_delete=django.db.models.
                                                deletion.CASCADE,
                                                related_name='carts',
                                                to=settings.
                                                AUTH_USER_MODEL)),],),
            migrations.CreateModel(name='Product', fields=[(
                'id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2,
                                              max_digits=8))]),
            migrations.CreateModel(
                name='Order_items',
                fields=[('id', models.BigAutoField(auto_created=True,
                                                   primary_key=True,
                                                   serialize=False,
                                                   verbose_name='ID')),
                        ('quantity', models.IntegerField()),
                        ('order', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='order_items', to='api.cart')),
                        ('product', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='order_items',
                            to='api.product')),],),
            migrations.CreateModel(
                name='Order',
                fields=[('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                        ('total_price', models.DecimalField(
                            decimal_places=2, max_digits=8)),
                        ('quantity', models.IntegerField()),
                        ('user', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='order',
                            to=settings.AUTH_USER_MODEL)),],),
            migrations.CreateModel(
                name='Cart_items',
                fields=[('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                        ('quantity', models.IntegerField()),
                        ('cart', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='items', to='api.cart'
                            )),
                        ('product', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='items', to='api.product')),],),
    ]
