# Generated by Django 4.2.2 on 2023-06-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
        ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_items', to='api.order'
                ),
            ),
        ]
